# Generated by Django 5.2.6 on 2025-09-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chicken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Give your chicken a ridiculous or majestic name', max_length=100)),
                ('breed', models.CharField(help_text='e.g., Apocalypse Rooster, Galactic Hen, Drama Queen', max_length=100)),
                ('description', models.TextField(help_text='Describe your chickens life philosophy in 250 words or less', max_length=250)),
                ('age', models.IntegerField(help_text='Age of the chicken (in chicken years, or human years, who cares)')),
            ],
        ),
    ]
