# Generated by Django 5.2.6 on 2025-09-08 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscapeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date & time of the daring escape')),
                ('method', models.CharField(help_text='How did they think this was going to work? (e.g., tunnel, fake mustache, bribery)', max_length=100)),
                ('success', models.BooleanField(default=False)),
                ('chicken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.chicken')),
            ],
        ),
    ]
