# Generated by Django 5.2.6 on 2025-09-08 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_escapeattempt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escapeattempt',
            options={'ordering': ['-date']},
        ),
    ]
